### ISSUE TITLE
[Bug]:  Party Frame members are inconsistently clickable

### ISSUE THREAD

**Issue by Atroskelis** [DelvUI/DelvUI#1254]
### What are you trying to do?

Trying to select a teammate in a party frame

### What is the expected behavior?

The respective party member (or myself)  should be targeted every time i click

### What actually happened?

Clicks work a percentage of the time, not always, but its enough for it to not be reliable

### Suggested solution

If you require i can try to record a video

No other frames have this issue, i can always click on the Player Unit frame and it works every time

### Logs

```shell
DelvUi 2.2.1.0
I don't have Umbra or anything that overlaps. It worked a few days ago.
```

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Atroskelis** [comment]
Apparently this is fixed by enabling "Special Mouse Clicks" and restarting game. Though i dont have a mouse with special buttons.

**Comment by YakudzaKY** [comment]
> Apparently this is fixed by enabling "Special Mouse Clicks" and restarting game. Though i dont have a mouse with special buttons.

have same trouble. Enabling this options fix this problem without game restart

**Comment by SSLink2010** [comment]
Also having same issue. While Special mouse clicks options does remedy the targeting issue. Still cannot right click party frame for sub command menu.

**Comment by namelessce** [comment]
I was having the same exact issues after updating using the previous update (Not 08/11/2024s). Checking that box allowed me to go back to DELVUI party frames, as I had to go to default since they weren't working.

**Comment by Atroskelis** [comment]
Fixed with last update
